### ISSUE TITLE
Nil value is created not where expected

### ISSUE THREAD

**Issue by Barf-Vader** [pkulchenko/serpent#38]
If you run the code below:
```lua		local tbl= {}
		tbl[2] = "stuff"
		serpent.line(tbl, {comment = false}
```

`serpent.line` outputs `{nil,"stuff"}`
Same thing happens with `serpent.block` and `serpent.dump` - the first value will be nil.

shouldn't the output be '{[2] = "stuff"}'?

If works fine if you start from 3:
```lua		local tbl= {}
		tbl[3] = "stuff"
		serpent.line(tbl, {comment = false}
```
`serpent.line` outputs `{[3] = "stuff"}`

**Comment by pkulchenko** [comment]
> shouldn't the output be '{[2] = "stuff"}'?

Not really. Both literals (`{[2] = "stuff"}` and `{nil, "stuff"}`) are equivalent for the purpose of reading from the table.

The reason for the different results is that the "length" of the first table is 2, but of the second table is 0 (the length is in quotes because it's not defined for tables with holes in them). The module produces sparse results (`{[2] = "stuff"}`), but only for elements with indexes that are larger than the "length" of the table.

Does it create a problem for you or you just noticed some inconsistency?

**Comment by Barf-Vader** [comment]
It's not a problem for me, it's just something I noticed.

**Comment by pkulchenko** [comment]
@Barf-Vader, ok, thank you for the update. I'll close the ticket then, since this is the expected behavior.
